# Generated by Django 3.2.6 on 2021-08-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='sub_tile',
            new_name='sub_title',
        ),
    ]
