# Generated by Django 3.2.6 on 2021-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sub_tile_carousel_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='action_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
